force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP ID-{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/IsAllocated__c.field-meta.xml
<CustomField>
    <fullName>IsAllocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAllocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>CPQ Developer</fullName>
            </value>
            <value>
                <fullName>LWC Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce QA Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJECT-{0000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Architects__c.field-meta.xml
<CustomField>
    <fullName>No_of_Architects__c</fullName>
    <label>No of  Architects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Designers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Designers__c</fullName>
    <label>No of Designers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Developers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Developers__c</fullName>
    <label>No of Developers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Testers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Testers__c</fullName>
    <label>No of Testers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Skills__c.field-meta.xml
<CustomField>
    <fullName>Project_Skills__c</fullName>
    <label>Project Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>CPQ Developer</fullName>
            </value>
            <value>
                <fullName>LWC Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce QA Tester</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PROJECT ASSIGNMENT-{0000}</displayFormat>
        <label>Project Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Project_Name__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rolled Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Skills__c/Project_Skills__c.object-meta.xml
<CustomObject>
    <label>Project Skills</label>
    <nameField>
        <displayFormat>PROJECT SKILL-{0000}</displayFormat>
        <label>Project Skills ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Skills__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Skills__c/fields/Project_Skills__c.field-meta.xml
<CustomField>
    <fullName>Project_Skills__c</fullName>
    <label>Project Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Skills__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <referenceTo>Skills__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skills__c/Skills__c.object-meta.xml
<CustomObject>
    <label>Skills</label>
    <nameField>
        <displayFormat>SKILL-{000}</displayFormat>
        <label>Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexTestClass.cls
@isTest
public class ApexTestClass {
       
      public static testMethod void validateAssignmentClass() {
          
          String reqSkills ='Salesforce Developer;Salesforce Administrator;CPQ Developer;LWC Developer;Salesforce QA Tester;Solution Architect';
          
          Project__c project = new Project__c(Project_Name__c = 'project1' ,Project_Skills__c = reqSkills, No_of_Developers__c = 1,No_of_Designers__c=1, No_of_Testers__c=1, No_of_Architects__c=1, No_of_Managers__c=1,Stage__c = 'Draft', Account_Name__c = '0010w00000xZ1HKAA0');
          insert project;
          
          Project__c project1 = new Project__c(Project_Name__c = 'project2' ,Project_Skills__c = reqSkills, No_of_Developers__c = 1,No_of_Designers__c=1, No_of_Testers__c=1, No_of_Architects__c=1, No_of_Managers__c=1,Stage__c = 'Draft', Account_Name__c = '0010w00000xZ1HKAA0');
          insert project1;
          
          List<Employee__c> empList = new List<Employee__c>();
          Employee__c emp1 = new Employee__c(Employee_Name__c='emp 1', Skills__c ='Salesforce Developer', Role__c='Developer', IsAllocated__c=false);
          empList.add(emp1);
           Employee__c emp2 = new Employee__c(Employee_Name__c='emp 2', Skills__c ='LWC Developer', Role__c='Designer', IsAllocated__c=false);
          empList.add(emp2);
           Employee__c emp3 = new Employee__c(Employee_Name__c='emp 3', Skills__c ='Salesforce QA Tester', Role__c='Tester', IsAllocated__c=false);
          empList.add(emp3);
           Employee__c emp4 = new Employee__c(Employee_Name__c='emp 4', Skills__c ='Salesforce Administrator', Role__c='Manager', IsAllocated__c=false);
          empList.add(emp4);
           Employee__c emp5 = new Employee__c(Employee_Name__c='emp 5', Skills__c ='Solution Architect', Role__c='Architect', IsAllocated__c=false);
          empList.add(emp5);
          Employee__c emp6 = new Employee__c(Employee_Name__c='emp 6', Skills__c ='Salesforce Developer', Role__c='Developer', IsAllocated__c=false);
          empList.add(emp6);
           Employee__c emp7 = new Employee__c(Employee_Name__c='emp 7', Skills__c ='LWC Developer', Role__c='Designer', IsAllocated__c=false);
          empList.add(emp7);
           Employee__c emp8 = new Employee__c(Employee_Name__c='emp 8', Skills__c ='Salesforce QA Tester', Role__c='Tester', IsAllocated__c=false);
          empList.add(emp8);
           Employee__c emp9 = new Employee__c(Employee_Name__c='emp 9', Skills__c ='Salesforce Administrator', Role__c='Manager', IsAllocated__c=false);
          empList.add(emp9);
           Employee__c emp10 = new Employee__c(Employee_Name__c='emp 10', Skills__c ='Solution Architect', Role__c='Architect', IsAllocated__c=false);
          empList.add(emp10);
          
          insert empList;
          
          
        
           AssignmentClass ac = new AssignmentClass();
           
           
           ac.assignEmployeesWithRelevantSkills( reqSkills ,1 , 1 , 1 , 1 , 1 , project.Id);
           
        List<String> res = reqSkills.split(';');
        System.assertEquals(6, res.size());
          
       // System.Debug(res);
        
       // List<Employee__c> empList2 = [Select Employee_Name__c, Skills__c, Role__c from Employee__c where Role__c= 'Developer' AND IsAllocated__c = false AND Skills__c IN :res];
        //List<Employee__c> empList3 = [Select Employee_Name__c, Skills__c, Role__c from Employee__c where Role__c= 'Designer' AND IsAllocated__c = false AND Skills__c IN :res];
        //List<Employee__c> empList4 = [Select Employee_Name__c, Skills__c, Role__c from Employee__c where Role__c= 'Tester' AND IsAllocated__c = false AND Skills__c IN :res];
        //List<Employee__c> empList5 = [Select Employee_Name__c, Skills__c, Role__c from Employee__c where Role__c= 'Architect' AND IsAllocated__c = false AND Skills__c IN :res];
       // List<Employee__c> empList6 = [Select Employee_Name__c, Skills__c, Role__c from Employee__c where Role__c= 'Manager' AND IsAllocated__c = false AND Skills__c IN :res];
      
          
           //System.assertEquals(0, empList2.size());
           //System.assertEquals(1, empList3.size());
          
          
          List<Employee__c> FinalEmpList = new List<Employee__c>();
          
          Integer i = 0, j = 0 , k = 0 , l = 0 , m = 0;
        
        // Developers
        for(Employee__c devEmp : empList)
        {
            if(i == 1)
            {
                break;
            }
            //devEmp.Project_Name__c = projectId ;
            FinalEmpList.add(devEmp);
            i++;
            
        }
          
          System.assertEquals(1, FinalEmpList.size());
          System.assertEquals(1, i);
          
          //System.assertEquals(1, empList.size());
          
          List<Project_Assignment__c> projectAssignmentList = new List<Project_Assignment__c>();
          
          for(Employee__c devEmployee : empList){
          
            Project_Assignment__c oneAssignment = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = devEmployee.Id , Status__c = 'Draft' );
            projectAssignmentList.add(oneAssignment);
        }
          
          insert projectAssignmentList;
          
          List<Project_Assignment__c> projectAssignmentList1 = new List<Project_Assignment__c>();
          for(Employee__c devEmployee1 : empList){
          
            Project_Assignment__c oneAssignment1 = new Project_Assignment__c( Project_Name__c = project1.Id ,Employee_Name__c = devEmployee1.Id , Status__c = 'Draft' );
            projectAssignmentList1.add(oneAssignment1);
        }
          
          insert projectAssignmentList1;
          
          String reqSkills1 ='Salesforce Developer;Salesforce Administrator;CPQ Developer;LWC Developer;Salesforce QA Tester;Solution Architect';
          
         // AfterAssignmentClass aac = new AfterAssignmentClass();
          
         // aac.afterAssignEmployeesWithRelevantSkills((string)reqSkills1, (Integer)1 ,(Integer)1 ,(Integer)1 ,(Integer)1 ,(Integer)1 , projectAssignmentList1 , projectAssignmentList);
          
          project.Stage__c='Initiated';
          update project;
          
          project.Stage__c='Delivered';
          update project;
          
          opportunityEstimationClass oc = new opportunityEstimationClass();
          oc.EstimationStageMethod();
          
          
          Map<String,Integer> emp = getEmployeeDetailsForScoping.getDetails(reqSkills);
          System.assertEquals(1, emp.get('Developer'));
    
          EmployeeQuery eq = new EmployeeQuery('Salesforce Developer', 1 , 'Developer');
          
          
          
          
         // aac.afterAssignEmployeesWithRelevantSkills(reqSkills , 1,1,1,1,1, );
          
         /* project1.Stage__c = 'Draft';
          List<Employee__c> empList1 = new List<Employee__c>();
          
          Employee__c emp11 = new Employee__c(Employee_Name__c='emp 11', Skills__c ='Solution Architect', Role__c='Architect', IsAllocated__c=false);
          empList1.add(emp11);
          Employee__c emp12 = new Employee__c(Employee_Name__c='emp 12', Skills__c ='Salesforce Developer', Role__c='Developer', IsAllocated__c=false);
          empList1.add(emp12);
           Employee__c emp13 = new Employee__c(Employee_Name__c='emp 13', Skills__c ='LWC Developer', Role__c='Designer', IsAllocated__c=false);
          empList1.add(emp13);
           Employee__c emp14 = new Employee__c(Employee_Name__c='emp 14', Skills__c ='Salesforce QA Tester', Role__c='Tester', IsAllocated__c=false);
          empList1.add(emp14);
           Employee__c emp15 = new Employee__c(Employee_Name__c='emp 15', Skills__c ='Salesforce Administrator', Role__c='Manager', IsAllocated__c=true);
          empList1.add(emp15);
           Employee__c emp16 = new Employee__c(Employee_Name__c='emp 16', Skills__c ='Solution Architect', Role__c='Architect', IsAllocated__c=true);
          empList1.add(emp16);
          
          insert empList1;
          
          update project1; */

       }
           
}