force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP ID-{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/IsAllocated__c.field-meta.xml
<CustomField>
    <fullName>IsAllocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAllocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>CPQ Developer</fullName>
            </value>
            <value>
                <fullName>LWC Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce QA Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skills__c/Skills__c.object-meta.xml
<CustomObject>
    <label>Skills</label>
    <nameField>
        <displayFormat>SKILL-{000}</displayFormat>
        <label>Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/getEmployeeDetailsForScoping.cls
public with sharing class getEmployeeDetailsForScoping {
    @AuraEnabled(cacheable=true)
    public static Map<String,Integer> getDetails(String Skill){

        List<String> res = Skill.split(';');
        System.Debug(res);

        List<aggregateresult> agr = [select count(ID), Role__c  from Employee__c where IsAllocated__c = False AND Skills__c IN :res group by Role__c];

         //List<aggregateresult> agr = [select count(ID), Role__c  from Employee__c where IsAllocated__c = False AND Skills__c= :Skill group by Role__c];
         system.debug(agr);

        Map<String,Integer> emplist = new Map<String,Integer>();

        integer Developer=0,Tester=0,Manager=0,Architect=0,Designer=0;

        for(aggregateresult aggr : agr)
        {
            if(aggr.get('Role__c') == 'Developer')
            {
                Developer = (integer)(aggr.get('expr0'));
            }

           else if(aggr.get('Role__c') == 'Tester')
            {
                Tester = (integer)(aggr.get('expr0'));
            }

            else if(aggr.get('Role__c') == 'Manager')
            {
                Manager = (integer)(aggr.get('expr0'));
            }

            else if(aggr.get('Role__c') == 'Designer')
            {
                Designer = (integer)(aggr.get('expr0'));
            }

            else if(aggr.get('Role__c') == 'Architect')
            {
                Architect = (integer)(aggr.get('expr0'));
            }    
        }
        
        // integer Developer =  (integer)(agr[0].get('expr0'));
		// integer Tester = (integer)(agr[1].get('expr0'));
        // integer Designer = (integer)(agr[2].get('expr0'));

        emplist.put('Developer',Developer);
        emplist.put('Tester',Tester);
        emplist.put('Designer',Designer);
        emplist.put('Manager',Manager);
        emplist.put('Architect',Architect);
        
          
        system.debug('Developer '+Developer);
    	system.debug('Designer '+Designer);
        system.debug('Tester '+Tester);
        System.debug(emplist);
       
       return emplist;
    }
    
}