force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP ID-{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/IsAllocated__c.field-meta.xml
<CustomField>
    <fullName>IsAllocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAllocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>CPQ Developer</fullName>
            </value>
            <value>
                <fullName>LWC Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce QA Tester</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PROJECT-{0000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Architects__c.field-meta.xml
<CustomField>
    <fullName>No_of_Architects__c</fullName>
    <label>No of  Architects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Designers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Designers__c</fullName>
    <label>No of Designers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Developers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Developers__c</fullName>
    <label>No of Developers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Testers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Testers__c</fullName>
    <label>No of Testers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Skills__c.field-meta.xml
<CustomField>
    <fullName>Project_Skills__c</fullName>
    <label>Project Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Administrator</fullName>
            </value>
            <value>
                <fullName>CPQ Developer</fullName>
            </value>
            <value>
                <fullName>LWC Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce QA Tester</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/Project_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PROJECT ASSIGNMENT-{0000}</displayFormat>
        <label>Project Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assignment__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Project_Name__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Assignments</relationshipLabel>
    <relationshipName>Project_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rolled Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Skills__c/Project_Skills__c.object-meta.xml
<CustomObject>
    <label>Project Skills</label>
    <nameField>
        <displayFormat>PROJECT SKILL-{0000}</displayFormat>
        <label>Project Skills ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Skills__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Skills__c/fields/Project_Skills__c.field-meta.xml
<CustomField>
    <fullName>Project_Skills__c</fullName>
    <label>Project Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Skills__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <referenceTo>Skills__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skills__c/Skills__c.object-meta.xml
<CustomObject>
    <label>Skills</label>
    <nameField>
        <displayFormat>SKILL-{000}</displayFormat>
        <label>Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AfterAssignmentClassTest.cls
@isTest
public class AfterAssignmentClassTest {
    
    public static testMethod void afterAssignTestMethod(){
        
         String reqSkills ='Salesforce Developer;Salesforce Administrator;CPQ Developer;LWC Developer;Salesforce QA Tester;Solution Architect';
        
         List<Project_Assignment__c> oldpaList = new List<Project_Assignment__c>();
         List<Project_Assignment__c> oldDraftpaList = new List<Project_Assignment__c>();
        
         Project__c project = new Project__c(Project_Name__c= 'project 1', Account_Name__c = '0010w00000xZ1HKAA0', Project_Skills__c= reqSkills, No_of_Architects__c=1, No_of_Designers__c=1, No_of_Developers__c=1, No_of_Managers__c=1, No_of_Testers__c=1);
        
         insert project;
        
         List<Employee__c> empList = new List<Employee__c>();
        
         Employee__c e1 = new Employee__c( Employee_Name__c = 'emp 1', IsAllocated__c = false , Role__c = 'Architect', Skills__c = 'Solution Architect' );
         Employee__c e2 = new Employee__c( Employee_Name__c = 'emp 2', IsAllocated__c = false , Role__c = 'Manager', Skills__c = 'Salesforce Administrator' );
         Employee__c e3 = new Employee__c( Employee_Name__c = 'emp 3', IsAllocated__c = false , Role__c = 'Designer', Skills__c = 'LWC Developer' );
         Employee__c e4 = new Employee__c( Employee_Name__c = 'emp 4', IsAllocated__c = false , Role__c = 'Tester', Skills__c = 'Salesforce QA Tester' );
         Employee__c e5 = new Employee__c( Employee_Name__c = 'emp 5', IsAllocated__c = false , Role__c = 'Developer', Skills__c = 'Salesforce Developer' );
         
         Employee__c e6 = new Employee__c( Employee_Name__c = 'emp 6', IsAllocated__c = true , Role__c = 'Architect', Skills__c = 'Solution Architect' );
         Employee__c e7 = new Employee__c( Employee_Name__c = 'emp 7', IsAllocated__c = true , Role__c = 'Manager', Skills__c = 'Salesforce Administrator' );
         Employee__c e8 = new Employee__c( Employee_Name__c = 'emp 8', IsAllocated__c = true , Role__c = 'Designer', Skills__c = 'LWC Developer' );
         Employee__c e9 = new Employee__c( Employee_Name__c = 'emp 9', IsAllocated__c = true , Role__c = 'Tester', Skills__c = 'Salesforce QA Tester' );
         Employee__c e10 = new Employee__c( Employee_Name__c = 'emp 10', IsAllocated__c = true , Role__c = 'Developer', Skills__c = 'Salesforce Developer' );
         
        
         empList.add(e1);
         empList.add(e2);
         empList.add(e3);
         empList.add(e4);
         empList.add(e5);
        
         empList.add(e6);
         empList.add(e7);
         empList.add(e8);
         empList.add(e9);
         empList.add(e10);
        
         insert empList;
        
        Project_Assignment__c oneAssignment1 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e1.Id, Status__c = 'Draft' );
        Project_Assignment__c oneAssignment2 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e2.Id, Status__c = 'Draft' );
        Project_Assignment__c oneAssignment3 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e3.Id, Status__c = 'Draft' );
        Project_Assignment__c oneAssignment4 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e4.Id, Status__c = 'Draft' );
        Project_Assignment__c oneAssignment5 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e5.Id, Status__c = 'Draft' );
        
        oldDraftpaList.add(oneAssignment1);
        oldDraftpaList.add(oneAssignment2);
        oldDraftpaList.add(oneAssignment3);
        oldDraftpaList.add(oneAssignment4);
        oldDraftpaList.add(oneAssignment5);
        
        insert oldDraftpaList;
        
        Project_Assignment__c oneAssignment6 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e6.Id, Status__c = 'Cancelled' );
        Project_Assignment__c oneAssignment7 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e7.Id, Status__c = 'Cancelled' );
        Project_Assignment__c oneAssignment8 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e8.Id, Status__c = 'Cancelled' );
        Project_Assignment__c oneAssignment9 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e9.Id, Status__c = 'Cancelled' );
        Project_Assignment__c oneAssignment10 = new Project_Assignment__c( Project_Name__c = project.Id ,Employee_Name__c = e10.Id, Status__c = 'Cancelled' );
        
        oldpaList.add(oneAssignment6);
        oldpaList.add(oneAssignment7);
        oldpaList.add(oneAssignment8);
        oldpaList.add(oneAssignment9);
        oldpaList.add(oneAssignment10);
        
        insert oldpaList;
        
        AfterAssignmentClass aac = new AfterAssignmentClass();
        
        aac.afterAssignEmployeesWithRelevantSkills((string)project.Project_Skills__c, 1,1,1,1,1, project.Id, oldpaList , oldDraftpaList);
    }
}